# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3efb124ceb8d25847f8db8500fc0facad11c36529e0b2bd1704d83c5eb2037a8116d0291bf650893ca02b1ddd0c620092bc376b935043f530d3e70c5392af3cb

test:
  secret_key_base: ead72b9a2d126cef73a0b2ca0a1f43427e76696ef754a9192bb3c13de05b380f6d012942bc01f943168847a9121b80907c3f47b85110a9929ab6fc60a5774bbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
